### ISSUE TITLE
(RSS/RO 1.12.3) RealFuels module appears twice, negative volume, incorrect fuel amount, issue is isolated to SEP 2.x

### ISSUE THREAD

**Issue by InfoTheGamer** [Kari1407/Starship-Expansion-Project#46]
Tank values are under what they should be in RO. In SEP 1.x, tanks show correct values and no duplicate RealFuels module appears on the parts. In SEP 2.x, the issues appear:

-Duplicate RealFuels modules on every tank part
-Filling one tank gives the total tank volume either (0.6/0.4) or a value that is significantly under the tank values for SEP 1.x
-Filling one tank gives the other duplicate a negative volume
-Testing in a skeleton install of RO yields the same results

**Comment by camelhai** [comment]
Mass values of the parts are also incorrect for me, most parts are  showing up as 0 tonnes.
Test Flight doesn't seem to work either, all engines have a 100% success chance

**Comment by Anomalia2022** [comment]
I have already taken note if this error and already working towards a fix. Hang tight and we will post an update soon.

**Comment by Anomalia2022** [comment]
To further help you, could you join the Discord and ping Anomalia so I can assist you further

**Comment by Kari1407** [comment]
This has been fixed for a while now

**Comment by Dupiter-AU** [comment]
This is not fixed, I am still having this exact problem on the latest version from CKAN (v2.0.2), KSP 1.12.5, latest version of RSS/RO

![Screenshot_20230627_123353](https://github.com/Kari1407/Starship-Expansion-Project/assets/82429716/6f56c56d-4325-4078-88ce-de5867cc9706)

Compared to a procedural Steel Stir Weld tank of approximately the same size;
![Screenshot_20230627_123410](https://github.com/Kari1407/Starship-Expansion-Project/assets/82429716/6faed1dd-62d4-4e7e-a271-63e7caee1064)
![Screenshot_20230627_123449](https://github.com/Kari1407/Starship-Expansion-Project/assets/82429716/08af5f37-c046-41dd-84a7-794a3c1605fd)

I can't find any problems in the RO config file, it _looks_ like the tank volume should be much greater ¯\_ (ツ)_/¯

If you need, KSP.log is attached;
[KSP.log](https://github.com/Kari1407/Starship-Expansion-Project/files/11877131/KSP.log)

**Comment by Fossilized4** [comment]
> This is not fixed, I am still having this exact problem on the latest version from CKAN (v2.0.2), KSP 1.12.5, latest version of RSS/RO
> 
> ![Screenshot_20230627_123353](https://user-images.githubusercontent.com/82429716/249018978-6f56c56d-4325-4078-88ce-de5867cc9706.png)
> 
> Compared to a procedural Steel Stir Weld tank of approximately the same size; ![Screenshot_20230627_123410](https://user-images.githubusercontent.com/82429716/249019081-6faed1dd-62d4-4e7e-a271-63e7caee1064.png) ![Screenshot_20230627_123449](https://user-images.githubusercontent.com/82429716/249019121-08af5f37-c046-41dd-84a7-794a3c1605fd.png)
> 
> I can't find any problems in the RO config file, it _looks_ like the tank volume should be much greater ¯_ (ツ)_/¯
> 
> If you need, KSP.log is attached; [KSP.log](https://github.com/Kari1407/Starship-Expansion-Project/files/11877131/KSP.log)

CKAN is not as up to date as the GitHub repository

**Comment by Kari1407** [comment]
just to elaborate on what fossil said, this issues are related to GitHub repository only, the issue is fixed, it's not on official releases yet, download the patches from the repository

**Comment by Dupiter-AU** [comment]
Oooooohhhhhhhhh, my bad, sorry!
